version: '3.8'

services:
  api_zdg:
    image: chrishubert/whatsapp-web-api:latest
    networks:
      - coolify
    volumes:
    - api_zdg_sessions:/usr/src/app/sessions
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.api_zdg.rule=Host(`apiwhatsapp.analyticaconnect.com`)
        - traefik.http.routers.api_zdg.entrypoints=websecure
        - traefik.http.routers.api_zdg.tls.certresolver=letsencryptresolver
        - traefik.http.routers.api_zdg.priority=1
        - traefik.http.routers.api_zdg.service=api_zdg
        - traefik.http.services.api_zdg.loadbalancer.server.port=3000
        - traefik.http.services.api_zdg.loadbalancer.passHostHeader=true

volumes:
  api_zdg_sessions:
    external: true
    name: api_zdg_sessions

networks:
  coolify:
    name: coolify
    external: true
